In [1]:
import defolt_picture as main

In [2]:
df = main.read_data()

In [3]:
df.describe()

,01.01.2018,01.02.2018,01.03.2018,01.04.2018,01.05.2018,01.06.2018,01.07.2018,01.08.2018,01.09.2018,01.10.2018,...,01.03.2022,01.04.2022,01.05.2022,01.06.2022,01.07.2022,01.08.2022,01.09.2022,01.10.2022,01.11.2022,01.12.2022
count,"4,251.00","4,536.00","5,073.00","5,880.00","6,536.00","7,135.00","7,836.00","8,579.00","9,487.00","10,660.00",...,"51,289.00","50,116.00","48,781.00","47,552.00","45,948.00","44,454.00","42,976.00","41,494.00","39,994.00","38,371.00"
mean,"3,305.25","3,321.67","3,387.97","3,426.21","3,507.32","3,573.87","3,571.59","3,594.99","3,543.10","3,507.99",...,"3,518.18","3,511.06","3,490.60","3,475.76","3,465.89","3,448.79","3,411.86","3,393.49","3,347.22","3,310.20"
std,"7,457.27","7,272.74","7,249.31","6,632.43","6,401.25","6,478.14","6,198.81","6,242.76","6,003.53","5,671.30",...,"2,547.02","2,513.37","2,437.84","2,408.70","2,380.70","2,367.79","2,317.33","2,366.76","2,234.40","2,189.31"
min,38.83,38.83,38.83,38.83,38.83,38.83,38.83,38.83,38.83,38.83,...,19.85,19.55,19.11,11.35,11.17,11.22,11.08,11.34,11.03,11.28
25%,"1,066.13","1,094.67","1,140.53","1,203.49","1,244.94","1,244.82","1,266.43","1,251.59","1,245.51","1,240.19",...,"1,518.28","1,524.59","1,529.24","1,532.53","1,539.57","1,538.64","1,533.23","1,525.10","1,516.16","1,508.11"
50%,"2,061.62","2,112.53","2,125.42","2,200.89","2,292.77","2,317.18","2,339.66","2,346.80","2,315.70","2,312.02",...,"3,016.16","3,023.55","3,029.42","3,033.27","3,037.33","3,029.31","3,012.82","2,997.69","2,980.31","2,961.18"
75%,"4,101.41","4,153.76","4,146.57","4,283.14","4,406.48","4,443.42","4,470.60","4,509.35","4,481.21","4,508.15",...,"4,847.34","4,835.90","4,796.32","4,756.30","4,730.96","4,689.91","4,624.09","4,566.35","4,495.34","4,436.38"
max,"194,654.05","194,654.05","194,654.05","194,654.05","194,654.05","194,654.05","194,654.05","194,654.05","194,654.05","194,654.05",...,"92,684.02","58,563.77","36,075.48","35,969.34","44,933.70","35,276.32","46,497.12","35,176.69","34,181.08","33,652.68"

In [4]:
rating_target = main.get_rating_target_values("высокий")

In [5]:
rating_values = rating_target[0]
trgt_rating = main.get_rating_target_per_years(df, rating_values)
trgt_rating

                 2018  2019  2020  2021  2022
экспресс без ФА  0.02  0.02  0.02  0.02  0.06
низкий           0.20  0.21  0.22  0.24  0.25
средний          0.26  0.27  0.30  0.34  0.35
высокий          0.52  0.50  0.46  0.41  0.34

In [6]:
backet_target = main.get_backet_target_values()

In [7]:
df_with_backet = main.construct_default_picture(
    df, 
    rating_target, 
    backet_target)

 month: 01.01.2018, rating: средний
 month: 01.01.2018, rating: низкий
 month: 01.01.2018, rating: экспресс без ФА
 month: 01.01.2018, rating: высокий
 month: 01.02.2018, rating: средний
 month: 01.02.2018, rating: низкий
 month: 01.02.2018, rating: экспресс без ФА
 month: 01.02.2018, rating: высокий
 month: 01.03.2018, rating: средний
 month: 01.03.2018, rating: низкий
 month: 01.03.2018, rating: экспресс без ФА
 month: 01.03.2018, rating: высокий
 month: 01.04.2018, rating: средний
 month: 01.04.2018, rating: низкий
 month: 01.04.2018, rating: экспресс без ФА
 month: 01.04.2018, rating: высокий
 month: 01.05.2018, rating: средний
 month: 01.05.2018, rating: низкий
 month: 01.05.2018, rating: экспресс без ФА
 month: 01.05.2018, rating: высокий
 month: 01.06.2018, rating: средний
 month: 01.06.2018, rating: низкий
 month: 01.06.2018, rating: экспресс без ФА
 month: 01.06.2018, rating: высокий
 month: 01.07.2018, rating: средний
 month: 01.07.2018, rating: низкий
 month: 01.07.2018, rating: экспресс без ФА
 month: 01.07.2018, rating: высокий
 month: 01.08.2018, rating: средний
 month: 01.08.2018, rating: низкий
 month: 01.08.2018, rating: экспресс без ФА
 month: 01.08.2018, rating: высокий
 month: 01.09.2018, rating: средний
 month: 01.09.2018, rating: низкий
 month: 01.09.2018, rating: экспресс без ФА
 month: 01.09.2018, rating: высокий
 month: 01.10.2018, rating: средний
 month: 01.10.2018, rating: низкий
 month: 01.10.2018, rating: экспресс без ФА
 month: 01.10.2018, rating: высокий
 month: 01.11.2018, rating: средний
 month: 01.11.2018, rating: низкий
 month: 01.11.2018, rating: экспресс без ФА
 month: 01.11.2018, rating: высокий
 month: 01.12.2018, rating: средний
 month: 01.12.2018, rating: низкий
 month: 01.12.2018, rating: экспресс без ФА
 month: 01.12.2018, rating: высокий
 month: 01.01.2019, rating: средний
 month: 01.01.2019, rating: низкий
 month: 01.01.2019, rating: экспресс без ФА
 month: 01.01.2019, rating: высокий
 month: 01.02.2019, rating: средний
 month: 01.02.2019, rating: низкий
 month: 01.02.2019, rating: экспресс без ФА
 month: 01.02.2019, rating: высокий
 month: 01.03.2019, rating: средний
 month: 01.03.2019, rating: низкий
 month: 01.03.2019, rating: экспресс без ФА
 month: 01.03.2019, rating: высокий
 month: 01.04.2019, rating: средний
 month: 01.04.2019, rating: низкий
 month: 01.04.2019, rating: экспресс без ФА
 month: 01.04.2019, rating: высокий
 month: 01.05.2019, rating: средний
 month: 01.05.2019, rating: низкий
 month: 01.05.2019, rating: экспресс без ФА
 month: 01.05.2019, rating: высокий
 month: 01.06.2019, rating: средний
 month: 01.06.2019, rating: низкий
 month: 01.06.2019, rating: экспресс без ФА
 month: 01.06.2019, rating: высокий
 month: 01.07.2019, rating: средний
 month: 01.07.2019, rating: низкий
 month: 01.07.2019, rating: экспресс без ФА
 month: 01.07.2019, rating: высокий
 month: 01.08.2019, rating: средний
 month: 01.08.2019, rating: низкий
 month: 01.08.2019, rating: экспресс без ФА
 month: 01.08.2019, rating: высокий
 month: 01.09.2019, rating: средний
 month: 01.09.2019, rating: низкий
 month: 01.09.2019, rating: экспресс без ФА
 month: 01.09.2019, rating: высокий
 month: 01.10.2019, rating: средний
 month: 01.10.2019, rating: низкий
 month: 01.10.2019, rating: экспресс без ФА
 month: 01.10.2019, rating: высокий
 month: 01.11.2019, rating: средний
 month: 01.11.2019, rating: низкий
 month: 01.11.2019, rating: экспресс без ФА
 month: 01.11.2019, rating: высокий
 month: 01.12.2019, rating: средний
 month: 01.12.2019, rating: низкий
 month: 01.12.2019, rating: экспресс без ФА
 month: 01.12.2019, rating: высокий
 month: 01.01.2020, rating: средний
 month: 01.01.2020, rating: низкий
 month: 01.01.2020, rating: экспресс без ФА
 month: 01.01.2020, rating: высокий
 month: 01.02.2020, rating: средний
 month: 01.02.2020, rating: низкий
 month: 01.02.2020, rating: экспресс без ФА
 month: 01.02.2020, rating: высокий
 month: 01.03.2020, rating: средний
 month: 01.03.2020, rating: низкий
 month: 01.03.2020, rating: экспресс без ФА
 month: 01.03.2020, rating: высокий
 month: 01.04.2020, rating: средний
 month: 01.04.2020, rating: низкий
 month: 01.04.2020, rating: экспресс без ФА
 month: 01.04.2020, rating: высокий
 month: 01.05.2020, rating: средний
 month: 01.05.2020, rating: низкий
 month: 01.05.2020, rating: экспресс без ФА
 month: 01.05.2020, rating: высокий
 month: 01.06.2020, rating: средний
 month: 01.06.2020, rating: низкий
 month: 01.06.2020, rating: экспресс без ФА
 month: 01.06.2020, rating: высокий
 month: 01.07.2020, rating: средний
 month: 01.07.2020, rating: низкий
 month: 01.07.2020, rating: экспресс без ФА
 month: 01.07.2020, rating: высокий
 month: 01.08.2020, rating: средний
 month: 01.08.2020, rating: низкий
 month: 01.08.2020, rating: экспресс без ФА
 month: 01.08.2020, rating: высокий
 month: 01.09.2020, rating: средний
 month: 01.09.2020, rating: низкий
 month: 01.09.2020, rating: экспресс без ФА
 month: 01.09.2020, rating: высокий
 month: 01.10.2020, rating: средний
 month: 01.10.2020, rating: низкий
 month: 01.10.2020, rating: экспресс без ФА
 month: 01.10.2020, rating: высокий
 month: 01.11.2020, rating: средний
 month: 01.11.2020, rating: низкий
 month: 01.11.2020, rating: экспресс без ФА
 month: 01.11.2020, rating: высокий
 month: 01.12.2020, rating: средний
 month: 01.12.2020, rating: низкий
 month: 01.12.2020, rating: экспресс без ФА
 month: 01.12.2020, rating: высокий
 month: 01.01.2021, rating: средний
 month: 01.01.2021, rating: низкий
 month: 01.01.2021, rating: экспресс без ФА
 month: 01.01.2021, rating: высокий
 month: 01.02.2021, rating: средний
 month: 01.02.2021, rating: низкий
 month: 01.02.2021, rating: экспресс без ФА
 month: 01.02.2021, rating: высокий
 month: 01.03.2021, rating: средний

KeyboardInterrupt: